package hookers

import (
	"bytes"
	"encoding/json"
	"fmt"
	"io"
	"io/ioutil"
	"net/http"
	"strings"

	"github.com/rusq/hubdeploy/internal/deploysrv"

	"github.com/goccy/go-yaml"
	"github.com/rusq/dlog"
)

const (
	ssuccess = "success"
	sfailure = "failure"
	serror   = "error"
)

type DockerHub struct {
	mapping map[string]map[string]deploysrv.Deployment // deployment = mapping[repo][tag]
}

// Generated by https://quicktype.io

type webhook struct {
	CallbackURL string     `json:"callback_url"`
	PushData    pushData   `json:"push_data"`
	Repository  repository `json:"repository"`
}

type pushData struct {
	Images   []string `json:"images"`
	PushedAt float64  `json:"pushed_at"`
	Pusher   string   `json:"pusher"`
	Tag      string   `json:"tag"`
}

type repository struct {
	CommentCount    int64   `json:"comment_count"`
	DateCreated     float64 `json:"date_created"`
	Description     string  `json:"description"`
	Dockerfile      string  `json:"dockerfile"`
	FullDescription string  `json:"full_description"`
	IsOfficial      bool    `json:"is_official"`
	IsPrivate       bool    `json:"is_private"`
	IsTrusted       bool    `json:"is_trusted"`
	Name            string  `json:"name"`
	Namespace       string  `json:"namespace"`
	Owner           string  `json:"owner"`
	RepoName        string  `json:"repo_name"`
	RepoURL         string  `json:"repo_url"`
	StarCount       int64   `json:"star_count"`
	Status          string  `json:"status"`
}

type callback struct {
	State       string `json:"state"`
	Description string `json:"description"`
	Context     string `json:"context"`
	TargetURL   string `json:"target_url"`
}

type docker struct {
	RepoName string   `yaml:"repo_name"`
	Tags     []string `yaml:"tags,omitempty"`
}

func (d *DockerHub) Type() string {
	return "hockerhub"
}

func (d *DockerHub) Register(dep deploysrv.Deployment) error {
	// ugly af
	dc, err := d.tryUnmarshal(dep.Payload)
	if err != nil {
		return err
	}
	d.add(dc, dep)

	return nil
}

const any = "*"

func (d *DockerHub) add(dc *docker, dep deploysrv.Deployment) {
	if d.mapping == nil {
		d.mapping = make(map[string]map[string]deploysrv.Deployment)
	}
	if d.mapping[dc.RepoName] == nil {
		d.mapping[dc.RepoName] = make(map[string]deploysrv.Deployment)
	}
	if len(dc.Tags) == 0 {
		d.mapping[dc.RepoName][any] = dep
	}
	for _, tag := range dc.Tags {
		d.mapping[dc.RepoName][tag] = dep
	}
}

func (d *DockerHub) tryUnmarshal(I interface{}) (*docker, error) {
	encoded, err := yaml.Marshal(I)
	if err != nil {
		return nil, err
	}
	var dc docker
	if err := yaml.Unmarshal(encoded, &dc); err != nil {
		return nil, err
	}
	return &dc, nil
}

func (d *DockerHub) Handler(j chan<- deploysrv.Job) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		var buf strings.Builder
		var wh webhook
		dec := json.NewDecoder(io.TeeReader(r.Body, &buf))
		if err := dec.Decode(&wh); err != nil {
			dlog.Printf("invalid body: %s", buf.String())
			http.Error(w, http.StatusText(http.StatusBadRequest), http.StatusBadRequest)
			return
		}

		tagsDP, ok := d.mapping[wh.Repository.RepoName]
		if !ok {
			dlog.Printf("no deployment for repository: %q", wh.Repository.RepoName)
			http.Error(w, "no deployment for this repository", http.StatusNotFound)
			return
		}

		dp, ok := tagsDP[any]
		if !ok {
			dp, ok = tagsDP[wh.PushData.Tag]
			if !ok {
				dlog.Printf("[%s] no deployment for tag: %q", wh.Repository.RepoName, wh.PushData.Tag)
				http.Error(w, "no deployment for this tag", http.StatusNotFound)
				return
			}
		}

		if dp.Disabled {
			dlog.Printf("[%s] deployment for tag: %q is disabled", wh.Repository.RepoName, wh.PushData.Tag)
			http.Error(w, "deployment for this tag is disabled", http.StatusNotFound)
			return
		}

		j <- deploysrv.Job{Dep: dp, CallbackURL: wh.CallbackURL}

		w.WriteHeader(http.StatusOK)
		w.Write([]byte(http.StatusText(http.StatusOK)))
	}
}

func (d *DockerHub) Callback(data deploysrv.CallbackData) error {
	state := ssuccess
	descr := data.Description
	if data.Error != nil {
		state = serror
		descr = data.Error.Error()
	}
	cb := callback{
		State:       state,
		Description: fmt.Sprintf("[%s]: %s", data.ID, descr),
		Context:     data.Context,
		TargetURL:   data.ResultsURL,
	}
	b, err := json.Marshal(cb)
	if err != nil {
		return err
	}
	// post the results
	dlog.Printf("%s> posting results to %s", data.ID, data.CallbackURL)
	dlog.Debugf("%s> data: %s", data.ID, string(b))
	resp, err := http.Post(data.CallbackURL, "application/json", bytes.NewReader(b))
	if err != nil {
		return err
	}
	if resp.StatusCode != http.StatusOK {
		return fmt.Errorf("invalid status code: %d", resp.StatusCode)
	}
	dlog.Printf("%s> post ok", data.ID)
	body, err := ioutil.ReadAll(resp.Body)
	if err != nil {
		dlog.Printf("%s> error reading body: %s", data.ID, err)
	}
	dlog.Debugf("%s> body: %s", data.ID, string(body))
	return nil
}
